database:
  maxOpenCoons: 64
  maxIdleConns: 64
  connMaxLifetime: 2
  connections:
    default:
      host: 172.16.10.25
      port: 3306
      username: b2c_oversea_test
      password: BPSBgEo9ZwKn!cj
      database: gordon
      charset: utf8mb4
redis:
  connections:
    default:
      host:
      port:
      db:
      password:
id:
  node: 1
  dataCenter: 1
  epoch: 2021-08-27 14:38:32

loggers:
  app: logs/app.log
  